import {Client} from 'pg';
import {readFileSync} from 'node:fs';
import {createHmac} from 'node:crypto';
import assert from 'node:assert/strict';
const base=process.env.TEST_API||'http://127.0.0.1:5081';
const password=process.env.DemoPassword||readFileSync('../../.local/runtime/demo-password.txt','utf8').trim();
const dbpass=process.env.PGPASSWORD||readFileSync('../../.local/runtime/db-password.txt','utf8').trim();
const db=new Client({host:'127.0.0.1',port:Number(process.env.PGPORT||55432),database:'kosova_test',user:'kosova',password:dbpass});await db.connect();
let checks=0;const results=[];
async function check(name,fn){try{await fn();checks++;results.push({name,status:'passed'});console.log('PASS '+name);}catch(e){console.error('FAIL '+name,e);throw e;}}
async function req(path,body,cookie='',token=''){const r=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{}),...(token?{'X-Booking-Token':token}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json().catch(()=>({}));return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function ok(path,body,cookie='',token=''){const r=await req(path,body,cookie,token);assert.equal(r.status,200,JSON.stringify(r));return r.data;}
const admin=(await req('/auth/login',{email:'admin@demo.local',password})).cookie;
const supplier=(await req('/auth/login',{email:'supplier@demo.local',password})).cookie;
const other=(await req('/auth/login',{email:'other@demo.local',password})).cookie;
assert.ok(admin&&supplier&&other);
const overview=await ok('/manage/overview',undefined,supplier);const s=overview.suppliers[0];const template=overview.vehicles[0];let vid,booking1,booking2,paid;
const start=new Date(Date.now()+30*86400000);start.setUTCHours(10,0,0,0);const end=new Date(start.getTime()+3*86400000);
const input={pickup:'prn',dropoff:'prn',start:start.toISOString(),end:end.toISOString(),age:30,extras:[]};
async function quote(vehicleId=vid,changes={}){return ok('/quotes',{...input,vehicleId,...changes});}
async function book(q){return ok('/bookings',{quoteId:q.id,locale:'de',termsVersion:q.snapshot.termsVersion,acceptTerms:true,customer:{name:'Integration Test',email:'test@example.invalid',phone:'+000000000',licenceYears:3},total:1});}
try {
await check('Supplier creates exact vehicle; cross-supplier read and write denied',async()=>{const r=await ok('/manage/vehicles',{supplierId:s.id,name:'Integration exact vehicle',spec:template.spec,rate:{...template.rate,prepay:false},policy:template.policy,reason:'Integration creation'},supplier);vid=r.id;const o=await ok('/manage/overview',undefined,other);assert.ok(!o.vehicles.some(v=>v.id===vid));assert.equal((await req('/manage/vehicles/'+vid,{name:'Intrusion',reason:'Unauthorized test'},other)).status,403);assert.equal((await req('/manage/vehicles/'+vid,{status:'published',reason:'Bypass'},supplier)).status,403);});
await check('Publication blocked without valid documents; quarantine and administrative approval',async()=>{await ok('/manage/vehicles/'+vid,{status:'submitted',reason:'Ready for review'},supplier);assert.equal((await req('/manage/vehicles/'+vid,{status:'published',reason:'Review'},admin)).status,400);for(const kind of ['registration','insurance']){const form=new FormData();form.set('supplierId',s.id);form.set('vehicleId',vid);form.set('kind',kind);form.set('expiresOn','2029-12-31');form.set('file',new Blob(['%PDF-1.4\nDemo test document\n%%EOF'],{type:'application/pdf'}),'test.pdf');const res=await fetch(base+'/api/manage/documents',{method:'POST',headers:{Cookie:supplier},body:form});assert.equal(res.status,200);const d=await res.json();assert.equal(d.state,'quarantined');await ok('/manage/documents/'+d.id+'/review',{state:'approved',reason:'Demonstration document only'},admin);}await ok('/manage/vehicles/'+vid,{status:'published',reason:'Approved valid demo documents'},admin);});
await check('Eligible vehicle appears in search for complete rental interval',async()=>{const cars=await ok('/search',input);assert.ok(cars.some(v=>v.id===vid));const ineligible=await ok('/search',{...input,age:18});assert.ok(!ineligible.some(v=>v.id===vid));});
await check('Quote totals cannot be tampered with and persisted quotes reject UPDATE',async()=>{const q=await quote();booking1=await book(q);const b=await ok('/bookings/'+booking1.id,undefined,'',booking1.accessToken);assert.equal(b.snapshot.total,q.snapshot.total);assert.ok(b.snapshot.total>1);await assert.rejects(db.query('UPDATE quotes SET total=1 WHERE id=$1',[q.id]),/immutable/);assert.equal((await req('/bookings/'+booking1.id)).status,401);assert.equal((await req('/bookings/'+booking1.id,undefined,other)).status,403);});
await check('Pending requests do not reserve inventory',async()=>{booking2=await book(await quote());const a=await db.query('SELECT count(*)::int AS n FROM allocations WHERE vehicle_id=$1',[vid]);assert.equal(a.rows[0].n,0);});
await check('REAL PostgreSQL concurrent acceptances cannot double-book one car',async()=>{const attempts=await Promise.all([booking1,booking2].map(b=>req('/bookings/'+b.id+'/transition',{status:'confirmed',reason:'Concurrent acceptance'},supplier)));assert.deepEqual(attempts.map(a=>a.status).sort(),[200,409]);const rows=await db.query('SELECT id,status FROM bookings WHERE id=ANY($1::uuid[])',[[booking1.id,booking2.id]]);assert.equal(rows.rows.filter(b=>b.status==='confirmed').length,1);const allocations=await db.query('SELECT count(*)::int AS n FROM allocations WHERE vehicle_id=$1',[vid]);assert.equal(allocations.rows[0].n,1);});
await check('Confirmed prices survive later rate changes and unavailable cars disappear',async()=>{const old=await ok('/bookings/'+booking1.id,undefined,'',booking1.accessToken);await ok('/manage/vehicles/'+vid,{rate:{...template.rate,daily:99000,prepay:false},reason:'Rate revision'},supplier);const current=await ok('/bookings/'+booking1.id,undefined,'',booking1.accessToken);assert.equal(current.snapshot.total,old.snapshot.total);assert.ok(!(await ok('/search',input)).some(v=>v.id===vid));});
await check('Cancellation releases inventory and maintains separate payment/refund state',async()=>{for(const b of [booking1,booking2]){await ok('/bookings/'+b.id+'/transition',{status:'cancelled',reason:'Integration cleanup'},'',b.accessToken);const saved=await ok('/bookings/'+b.id,undefined,'',b.accessToken);assert.equal(saved.status,'cancelled');assert.equal(saved.refund_state,'none');}assert.ok((await ok('/search',input)).some(v=>v.id===vid));});
await check('Document expiry blocks new quotes and supplier acceptance',async()=>{const q=await quote();const b=await book(q);await db.query("UPDATE documents SET expires_on=CURRENT_DATE-1 WHERE vehicle_id=$1 AND kind='insurance'",[vid]);assert.equal((await req('/quotes',{...input,vehicleId:vid})).status,409);assert.equal((await req('/bookings/'+b.id+'/transition',{status:'confirmed',reason:'Expired document test'},supplier)).status,409);await ok('/bookings/'+b.id+'/transition',{status:'declined',reason:'Cannot provide valid documents'},supplier);await db.query("UPDATE documents SET expires_on='2029-12-31' WHERE vehicle_id=$1",[vid]);});
await check('External bookings use the same database exclusion protection',async()=>{const block=await ok('/manage/allocations',{vehicleId:vid,start:input.start,end:input.end,kind:'external',reason:'External booking'},supplier);assert.equal((await req('/manage/allocations',{vehicleId:vid,start:input.start,end:input.end,kind:'maintenance',reason:'Overlap'},supplier)).status,409);await ok('/manage/allocations/'+block.id+'/remove',{reason:'Cancelled external booking'},supplier);});
await check('Test prepayment creates a timed hold and payment creation is idempotent',async()=>{await ok('/manage/vehicles/'+vid,{rate:{...template.rate,prepay:true},reason:'Prepayment test'},supplier);paid=await book(await quote());const accepted=await ok('/bookings/'+paid.id+'/transition',{status:'confirmed',reason:'Accept with payment'},supplier);assert.equal(accepted.status,'awaiting_payment');const [p1,p2]=await Promise.all([ok('/bookings/'+paid.id+'/payment',{},'',paid.accessToken),ok('/bookings/'+paid.id+'/payment',{},'',paid.accessToken)]);assert.equal(p1.id,p2.id);paid.payment=p1;});
await check('Signed webhook verification, duplicate and out-of-order events',async()=>{const ev={eventId:'integration-'+paid.id,paymentId:paid.payment.id,state:'succeeded'};const body=JSON.stringify(ev);const bad=await fetch(base+'/api/payments/test/webhook',{method:'POST',headers:{'Content-Type':'application/json','X-Test-Signature':'invalid'},body});assert.equal(bad.status,401);const signature=createHmac('sha256','local-test-webhook-key-not-for-production').update(body).digest('hex');for(let i=0;i<2;i++){const r=await fetch(base+'/api/payments/test/webhook',{method:'POST',headers:{'Content-Type':'application/json','X-Test-Signature':signature},body});assert.equal(r.status,200);}await ok('/test-payments/'+paid.payment.id+'/complete',{state:'failed'},'',paid.accessToken);const b=await ok('/bookings/'+paid.id,undefined,'',paid.accessToken);assert.equal(b.status,'confirmed');assert.equal(b.payment_state,'paid');assert.equal(b.payments.length,1);assert.equal(b.payments[0].state,'succeeded');});
await check('Cancellation and repeated refunds remain consistent',async()=>{await ok('/bookings/'+paid.id+'/transition',{status:'cancelled',reason:'Customer cancellation'},'',paid.accessToken);let b=await ok('/bookings/'+paid.id,undefined,'',paid.accessToken);assert.equal(b.refund_state,'requested');await ok('/manage/bookings/'+paid.id+'/refund',{reason:'Full refund under demo conditions'},admin);await ok('/manage/bookings/'+paid.id+'/refund',{reason:'Retry same refund'},admin);b=await ok('/bookings/'+paid.id,undefined,'',paid.accessToken);assert.equal(b.refund_state,'refunded');const refunds=await db.query('SELECT count(*)::int AS n FROM refunds WHERE payment_id=$1',[paid.payment.id]);assert.equal(refunds.rows[0].n,1);});
await check('Background expiry releases timed holds and persists accurate localized notification',async()=>{const b=await book(await quote());await ok('/bookings/'+b.id+'/transition',{status:'confirmed',reason:'Temporary hold'},supplier);await db.query("UPDATE bookings SET payment_due=now()-interval '1 minute' WHERE id=$1",[b.id]);await new Promise(r=>setTimeout(r,6500));const saved=await ok('/bookings/'+b.id,undefined,'',b.accessToken);assert.equal(saved.status,'expired');assert.ok(saved.notifications.some(n=>n.status==='expired'&&n.locale==='de'));const rows=await db.query('SELECT count(*)::int AS n FROM allocations WHERE booking_id=$1',[b.id]);assert.equal(rows.rows[0].n,0);});
await check('Support cases resolved and audit records available through admin interfaces',async()=>{const c=await ok('/support',{email:'support@example.invalid',message:'Integration assistance'});await ok('/manage/operations/'+c.id,{state:'resolved',reason:'Handled in operations'},admin);const events=await ok('/manage/audit',undefined,admin);assert.ok(events.some(e=>e.action==='operation.update'&&e.reason==='Handled in operations'));assert.equal((await req('/manage/audit',undefined,supplier)).status,403);});
await check('Replacement leaves original car unchanged until secure customer acceptance',async()=>{await ok('/manage/vehicles/'+vid,{rate:{...template.rate,prepay:false},reason:'Pay at pickup'},supplier);const b=await book(await quote());await ok('/bookings/'+b.id+'/transition',{status:'confirmed',reason:'Replacement scenario'},supplier);const candidate=overview.vehicles.find(v=>v.id!==vid&&v.status==='published');const proposal=await ok('/manage/bookings/'+b.id+'/replacement',{vehicleId:candidate.id,reason:'Operational replacement proposal'},supplier);let saved=await ok('/bookings/'+b.id,undefined,'',b.accessToken);assert.equal(saved.vehicle_id,vid);assert.equal((await req('/bookings/'+b.id+'/replacement/'+proposal.id,{accept:true,termsVersion:saved.snapshot.termsVersion},supplier,'invalid')).status,401);const p=saved.proposals.find(x=>x.id===proposal.id);await ok('/bookings/'+b.id+'/replacement/'+proposal.id,{accept:true,termsVersion:p.snapshot.termsVersion},'',b.accessToken);saved=await ok('/bookings/'+b.id,undefined,'',b.accessToken);assert.equal(saved.vehicle_id,candidate.id);assert.equal(saved.proposals[0].state,'accepted');await ok('/bookings/'+b.id+'/transition',{status:'cancelled',reason:'Finish replacement test'},'',b.accessToken);});
await check('Only completed bookings can review; moderation is administrative',async()=>{const b=await book(await quote());assert.equal((await req('/bookings/'+b.id+'/review',{rating:5,text:'Test review'},'',b.accessToken)).status,400);await ok('/bookings/'+b.id+'/transition',{status:'confirmed',reason:'Review test setup'},supplier);await db.query("UPDATE bookings SET status='completed' WHERE id=$1",[b.id]);await db.query('DELETE FROM allocations WHERE booking_id=$1',[b.id]);const r=await ok('/bookings/'+b.id+'/review',{rating:4,text:'Verified integration review'},'',b.accessToken);assert.equal((await req('/manage/operations/'+r.id,{state:'published',reason:'Supplier tries moderation'},supplier)).status,403);await ok('/manage/operations/'+r.id,{state:'published',reason:'Moderated test review'},admin);assert.equal((await req('/bookings/'+b.id+'/review',{rating:5,text:'Duplicate'},'',b.accessToken)).status,409);});
console.log(`\n${checks} integration checks passed against real PostgreSQL.`);
}finally{await db.end();}
