'use client';
import {useState,useEffect,useCallback,createContext,useContext,FormEvent} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {useRouter,useSearchParams} from 'next/navigation';
import {ArrowRight,ArrowLeft,MapPin,Car,Check,Users,Suitcase,GasPump,Gear,ShieldCheck,Clock,AirplaneTilt,List,CalendarBlank,ArrowUpRight,CheckCircle,WarningCircle} from '@phosphor-icons/react';
import {api,Data} from '@/lib/api';
import {dictionaries,Locale,TextKey,money,date} from '@/lib/i18n';
import Dashboard from './Dashboard';
const Context=createContext<{locale:Locale,t:(k:TextKey|string)=>string}>({locale:'en',t:k=>k});
export const useText=()=>useContext(Context);
export function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>;}
export function Notice({children,error=false}:{children:React.ReactNode,error?:boolean}){return <div className={`notice ${error?'error':''}`} role={error?'alert':'status'}>{error?<WarningCircle size={20}/>:<CheckCircle size={20}/>}<div>{children}</div></div>;}
export function Status({value}:{value:string}){const {t}=useText();return <span className={`status status-${value}`}>{t(value==='pending'?'pendingState':value==='draft'?'draftState':value)}</span>;}
export function ErrorMessage({code}:{code:string}) {const {locale,t}=useText();const messages:Record<string,string[]>={vehicle_unavailable:['This vehicle is no longer available. Please search again.','Kjo veturë nuk është më e lirë. Kërkoni përsëri.','Dieses Fahrzeug ist nicht mehr verfügbar. Bitte erneut suchen.'],conflict:['This request conflicts with an existing record or reservation. Refresh and try again.','Kërkesa bie ndesh me një regjistrim ose rezervim ekzistues. Rifreskoni dhe provoni përsëri.','Konflikt mit einem bestehenden Eintrag oder einer Reservierung. Bitte aktualisieren.'],quote_expired:['Your quote expired. Return to the vehicle to request a fresh quote.','Oferta ka skaduar. Kthehuni te vetura për një ofertë të re.','Ihr Angebot ist abgelaufen. Fordern Sie beim Fahrzeug ein neues Angebot an.'],invalid_interval:['Choose future dates with a return after pickup, within the allowed rental duration.','Zgjidhni data të ardhshme me kthim pas marrjes, brenda kohëzgjatjes së lejuar.','Wählen Sie zukünftige Daten mit Rückgabe nach Abholung innerhalb der erlaubten Mietdauer.'],ambiguous_datetime:['This time is ambiguous or unavailable due to daylight saving. Choose another time.','Kjo orë është e paqartë për shkak të ndryshimit sezonal. Zgjidhni një tjetër.','Diese Uhrzeit ist wegen der Zeitumstellung nicht eindeutig oder ungültig. Wählen Sie eine andere.'],insufficient_response_time:['Pickup is too soon for the supplier response window. Choose a later pickup.','Marrja është shumë afër afatit të përgjigjes. Zgjidhni një orar më të vonë.','Die Abholung liegt vor Ablauf der Antwortfrist. Wählen Sie einen späteren Termin.'],invalid_credentials:['Email or password is incorrect.','Emaili ose fjalëkalimi është i pasaktë.','E-Mail oder Passwort ist falsch.'],unauthorized:['Please sign in or use your private booking link.','Identifikohuni ose përdorni lidhjen private.','Bitte anmelden oder privaten Buchungslink verwenden.'],documents_expired:['Required vehicle documents do not cover these dates.','Dokumentet e veturës nuk mbulojnë këto data.','Die Fahrzeugdokumente gelten nicht für diesen Zeitraum.'],driver_ineligible:['The driver age does not meet this supplier’s conditions.','Mosha e shoferit nuk i plotëson kushtet.','Das Fahreralter entspricht nicht den Bedingungen.']};return <Notice error>{messages[code]?.[['en','sq','de'].indexOf(locale)]||t('error')}</Notice>;}
export default function Marketplace({locale,path}:{locale:Locale,path:string[]}){
 const [menu,setMenu]=useState(false);const t=(k:TextKey|string)=>(dictionaries[locale] as Record<string,string>)[k]||k;
 useEffect(()=>{document.documentElement.lang=locale;},[locale]);
 const page=path[0]||'home';
 return <Context.Provider value={{locale,t}}><a href="#main" className="skip">{t('skip')}</a><div className="demo-banner">{t('demo')}</div><header><div className="header-inner"><Link className="brand" href={`/${locale}`}><span className="brand-mark"><Car weight="fill" size={25}/></span><span>Kosova <b>Rent-A-Car</b></span></Link><button className="icon-button mobile-menu" aria-label="Menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}><List size={24}/></button><nav className={menu?'open':''} aria-label="Main navigation"><Link href={`/${locale}`}>{t('explore')}</Link><Link href={`/${locale}/guide`}>{t('guidance')}</Link><Link href={`/${locale}/booking`}>{t('bookings')}</Link><Link href={`/${locale}/support`}>{t('support')}</Link></nav><div className="language"><select aria-label="Language" value={locale} onChange={e=>{const url=new URL(window.location.href);url.pathname=url.pathname.replace(/^\/(en|sq|de)/,'/'+e.target.value);window.location.assign(url.toString());}}><option value="en">EN</option><option value="sq">SQ</option><option value="de">DE</option></select></div></div></header><main id="main">
 {page==='home'?<Home/>:page==='search'?<SearchResults/>:page==='vehicle'?<VehicleDetails id={path[1]}/>:page==='checkout'?<Checkout/>:page==='booking'?<Booking id={path[1]}/>:page==='supplier'?<Supplier id={path[1]}/>:page==='support'?<Support/>:page==='guide'||page==='airport'||['terms','privacy','cancellation'].includes(page)?<ContentPage page={page}/>:page==='login'?<Login/>:page==='dashboard'||page==='admin'?<Dashboard/>:<div className="container section"><h1>{t('notFound')}</h1><Link href={`/${locale}`}>{t('home')}</Link></div>}
 </main><footer><div className="container footer-grid"><div><Link className="brand" href={`/${locale}`}>Kosova <b>Rent-A-Car</b></Link><p>{t('footer')}</p><small>Prishtina · Kosovo</small></div><div><Link href={`/${locale}/guide`}>{t('guidance')}</Link><Link href={`/${locale}/support`}>{t('support')}</Link><Link href={`/${locale}/login`}>{t('partners')}</Link></div><div>{['privacy','terms','cancellation'].map(k=><Link key={k} href={`/${locale}/${k}`}>{t(k)}</Link>)}</div></div><div className="container footer-bottom">© {new Date().getFullYear()} Kosova Rent-A-Car <span>{t('draft')}</span></div></footer></Context.Provider>;
}
function defaults(){const d=new Date();d.setDate(d.getDate()+7);const e=new Date(d);e.setDate(e.getDate()+4);return {pickup:'prn',dropoff:'prn',start:d.toISOString().slice(0,10)+'T10:00',end:e.toISOString().slice(0,10)+'T10:00',age:30};}
export function SearchForm({compact=false}:{compact?:boolean}){
 const {locale,t}=useText();const router=useRouter();const params=useSearchParams();const [form,setForm]=useState(defaults);const [same,setSame]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(params.has('pickup')){const s=Object.fromEntries(params.entries());setForm(p=>({...p,...s,age:Number(s.age||30)}));setSame(s.pickup===s.dropoff);}},[params]);
 const update=(key:string,value:string|number)=>setForm(f=>({...f,[key]:value}));
 async function search(e:FormEvent){e.preventDefault();setBusy(true);setError('');try {await api('/time',{start:form.start,end:form.end});const q=new URLSearchParams({...form,age:String(form.age),dropoff:same?form.pickup:form.dropoff});router.push(`/${locale}/search?${q}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className={`search-form ${compact?'compact':''}`} onSubmit={search}><div className="search-fields"><Field label={t('pickup')}><select value={form.pickup} onChange={e=>update('pickup',e.target.value)}><option value="prn">{t('airport')}</option><option value="prishtina">{t('city')}</option></select></Field>{!same&&<Field label={t('dropoff')}><select value={form.dropoff} onChange={e=>update('dropoff',e.target.value)}><option value="prn">{t('airport')}</option><option value="prishtina">{t('city')}</option></select></Field>}<Field label={t('pickupDate')}><input required type="datetime-local" value={form.start} onChange={e=>update('start',e.target.value)}/></Field><Field label={t('returnDate')}><input required type="datetime-local" value={form.end} onChange={e=>update('end',e.target.value)}/></Field><Field label={t('age')}><input required type="number" min="18" max="99" value={form.age} onChange={e=>update('age',Number(e.target.value))}/></Field><button className="button" disabled={busy}>{busy?t('loading'):t('search')}<ArrowRight size={19}/></button></div><div className="search-bottom"><label className="check"><input type="checkbox" checked={same} onChange={e=>setSame(e.target.checked)}/>{t('sameReturn')}</label><small>{t('searchNote')}</small></div>{error&&<ErrorMessage code={error}/>}</form>;
}
function Home(){const {locale,t}=useText();return <><section className="hero container"><div className="hero-copy"><p className="eyebrow"><span/>{t('eyebrow')}</p><h1>{t('hero').split('\n').map((s,i)=><span key={s} className={i?'accent':''}>{s}<br/></span>)}</h1><p className="lead">{t('intro')}</p><div className="hero-tags"><span><MapPin size={18}/>Prishtina</span><span><AirplaneTilt size={18}/>PRN</span></div></div><div className="hero-image empty-photo" role="img" aria-label={t('photoPending')}/></section><div className="container search-home"><SearchForm/></div><section className="container section how"><div className="section-heading"><p className="eyebrow">{t('how')}</p><h2>{t('journey')}</h2><p>{t('journeyText')}</p></div><div className="steps">{[1,2,3].map((n)=><article key={n}><span className="step-number">0{n}</span><h3>{t(`how${n}`)}</h3><p>{t(`how${n}text`)}</p></article>)}</div></section><section className="container airport-panel"><div className="airport-icon"><AirplaneTilt size={56} weight="light"/></div><div><p className="eyebrow">PRN · PRISHTINA</p><h2>{t('airportTitle')}</h2><p>{t('airportText')}</p></div><Link className="text-link" href={`/${locale}/airport`}>{t('airportLink')}<ArrowRight size={20}/></Link></section></>;}
function useSearchInput(){const params=useSearchParams();const query=params.toString();const [input,setInput]=useState<Data|null>(null);const [error,setError]=useState('');useEffect(()=>{let live=true;const p=Object.fromEntries(new URLSearchParams(query));if(!p.start||!p.end){setError('invalid_interval');return;}api('/time',{start:p.start,end:p.end}).then(times=>{if(live){setInput({...p,...times,age:Number(p.age)});setError('');}}).catch(e=>live&&setError(e.message));return()=>{live=false};},[query]);return {input,error,query};}
function SearchResults(){
 const {locale,t}=useText();const {input,error:inputError,query}=useSearchInput();const [cars,setCars]=useState<Data[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [filters,setFilters]=useState<Record<string,string>>({});const [sort,setSort]=useState('low');
 useEffect(()=>{if(!input)return;let live=true;setLoading(true);api<Data[]>('/search',input).then(x=>live&&setCars(x)).catch(e=>live&&setError(e.message)).finally(()=>live&&setLoading(false));return()=>{live=false};},[input]);
 const filtered=cars.filter(c=>(!filters.category||c.spec.category===filters.category)&&(!filters.transmission||c.spec.transmission===filters.transmission)&&(!filters.fuel||c.spec.fuel===filters.fuel)&&(!filters.supplier||c.supplier_id===filters.supplier)&&(!filters.seats||c.spec.seats>=Number(filters.seats))&&(!filters.price||c.price.total<=Number(filters.price)*100)&&(!filters.deposit||c.policy.deposit<=Number(filters.deposit)*100)&&(!filters.mileage||c.policy.mileageDaily>=Number(filters.mileage))).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name)||a.id.localeCompare(b.id):(sort==='high'?-1:1)*(a.price.total-b.price.total)||a.id.localeCompare(b.id));
 const filter=(k:string,v:string)=>setFilters(f=>({...f,[k]:v}));
 return <div className="container section"><SearchForm compact/><div className="page-heading"><div><p className="eyebrow">{t('explore')}</p><h1>{t('results')}</h1><p>{t('resultNote')}</p></div></div>{(error||inputError)&&<ErrorMessage code={error||inputError}/>}<div className="results-layout"><aside className="filter-panel"><div className="row"><h3>{t('filters')}</h3><button className="link-button" onClick={()=>setFilters({})}>{t('reset')}</button></div>{['category','transmission','fuel','supplier'].map(k=><Field key={k} label={t(k)}><select value={filters[k]||''} onChange={e=>filter(k,e.target.value)}><option value="">{t('all')}</option>{Array.from(new Set(cars.map(c=>k==='supplier'?c.supplier_id:c.spec[k]))).map(v=><option key={v} value={v}>{k==='supplier'?cars.find(c=>c.supplier_id===v)?.supplier_name:t(v.toLowerCase())}</option>)}</select></Field>)}{['seats','mileage','price','deposit'].map(k=><Field key={k} label={t(k==='price'?'maxPrice':k==='deposit'?'maxDeposit':k)}><input type="number" min="0" placeholder={t('any')} value={filters[k]||''} onChange={e=>filter(k,e.target.value)}/></Field>)}</aside><div><div className="results-toolbar"><span>{filtered.length} {t('filtersApplied')}</span><Field label={t('sort')}><select aria-label={t('sort')} value={sort} onChange={e=>setSort(e.target.value)}><option value="low">{t('priceLow')}</option><option value="high">{t('priceHigh')}</option><option value="name">{t('nameSort')}</option></select></Field></div>{loading&&!inputError?<div className="loading" role="status">{t('loading')}</div>:filtered.length===0?<div className="empty"><Car size={40}/><h2>{t('noResults')}</h2><p>{t('noResultsText')}</p><button className="button secondary" onClick={()=>setFilters({})}>{t('reset')}</button></div>:<div className="car-list">{filtered.map(c=><CarCard key={c.id} car={c} href={`/${locale}/vehicle/${c.id}?${query}`}/>)}</div>}</div></div></div>;
}
function CarArt({car,large=false}:{car:Data,large?:boolean}){const {t}=useText();const hasImage=car.spec?.image?.startsWith('/api/images/');return <div className={`car-art ${large?'large':''} ${hasImage?'':'empty-photo'}`} role={hasImage?undefined:'img'} aria-label={hasImage?undefined:t('photoPending')}>{hasImage&&<Image src={car.spec.image} alt={car.name} fill sizes={large?'(max-width: 800px) 100vw, 60vw':'(max-width: 800px) 100vw, 300px'}/>}<span className="car-category">{t((car.spec?.category||'compact').toLowerCase())}</span>{hasImage&&<small>{car.name}</small>}</div>;}
function Specs({car}:{car:Data}){const {t}=useText();return <div className="specs"><span><Gear size={17}/>{t(car.spec.transmission.toLowerCase())}</span><span><Users size={17}/>{car.spec.seats} {t('seats')}</span><span><Suitcase size={17}/>{car.spec.luggage} {t('luggage')}</span><span><GasPump size={17}/>{t(car.spec.fuel.toLowerCase())}</span>{car.spec.ac&&<span><Check size={17}/>{t('ac')}</span>}</div>;}
function CarCard({car:c,href}:{car:Data,href:string}){const {locale,t}=useText();return <article className="car-card"><CarArt car={c}/><div className="car-info"><small>{c.supplier_name}</small><h2><Link href={href}>{c.name}</Link></h2>{c.review_count>0&&<small>{Number(c.verified_rating).toFixed(1)} / 5 · {c.review_count} {t('verifiedBooking')}</small>}<Specs car={c}/><div className="car-conditions"><span><MapPin size={17}/>{c.spec.pickupMethod}</span><span><Check size={17}/>{c.policy.mileageDaily} km / {t('daily').split(' ')[0]}</span><span><ShieldCheck size={17}/>{money(c.policy.deposit,locale)} {t('deposit').toLowerCase()}</span></div></div><div className="car-price"><span className="status">{t('requestType')}</span><div><small>{t('total')}</small><strong>{money(c.price.total,locale)}</strong><small>{money(Math.round(c.price.total/c.price.days),locale)} {t('daily')}</small></div><small>{t('payNow')}: {money(c.price.payNow,locale)}<br/>{t('payPickup')}: {money(c.price.payAtPickup,locale)}</small><Link className="button" href={href}>{t('details')}<ArrowRight size={18}/></Link></div></article>;}
function Price({snapshot:s}:{snapshot:Data}){const {locale,t}=useText();return <div className="price-breakdown"><h3>{t('quote')}</h3>{s.lines.map((l:Data,i:number)=><div className="row" key={i}><span>{t(l.key)}{l.quantity>1?` × ${l.quantity}`:''}</span><span>{money(l.amount,locale)}</span></div>)}<div className="row total"><strong>{t('total')}</strong><strong>{money(s.total,locale)}</strong></div><div className="row"><span>{t('payNow')}</span><b>{money(s.payNow,locale)}</b></div><div className="row"><span>{t('payPickup')}</span><b>{money(s.payAtPickup,locale)}</b></div><div className="deposit-box"><ShieldCheck size={22}/><div><b>{money(s.deposit,locale)} {t('deposit')}</b><small>{s.policy.depositMethod}</small></div></div><small>{t('taxNote')}</small></div>;}
function Trip({s}:{s:Data}){const {locale,t}=useText();return <div className="trip"><div><MapPin size={20}/><div><small>{t('pickup')}</small><b>{t(s.pickup==='prn'?'airport':'city')}</b><span>{date(s.start,locale)}</span></div></div><div><MapPin size={20}/><div><small>{t('dropoff')}</small><b>{t(s.dropoff==='prn'?'airport':'city')}</b><span>{date(s.end,locale)}</span></div></div></div>;}
function Policies({policy:p}:{policy:Data}){const {t}=useText();return <div className="policies"><h2>{t('conditions')}</h2><small>{t('policyReview')}</small>{[['documents','documents'],['insurance','insurance'],['fuelPolicy','fuel'],['crossBorder','crossBorder'],['cancellation','cancellation'],['pickupInstructions','pickup'],['returnInstructions','return']].map(([label,key])=><details key={key} open={key==='documents'}><summary>{t(label)}</summary><p>{p[key]||t('unconfigured')}</p></details>)}</div>;}
function VehicleDetails({id}:{id:string}){
 const {locale,t}=useText();const {input,error:inputError,query}=useSearchInput();const router=useRouter();const [car,setCar]=useState<Data|null>(null);const [quote,setQuote]=useState<Data|null>(null);const [extras,setExtras]=useState<string[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{api('/vehicles/'+id).then(setCar).catch(e=>setError(e.message));},[id]);
 useEffect(()=>{if(!input||!car)return;let live=true;setQuote(null);api('/quotes',{...input,vehicleId:id,extras}).then(q=>live&&setQuote(q)).catch(e=>live&&setError(e.message));return()=>{live=false};},[input,car,id,extras]);
 function checkout(){if(!quote)return;setBusy(true);sessionStorage.setItem('quote:'+quote.id,JSON.stringify(quote));router.push(`/${locale}/checkout?quote=${quote.id}`);}
 return <div className="container section"><Link className="back" href={`/${locale}/search?${query}`}><ArrowLeft/>{t('back')}</Link>{(error||inputError)&&<ErrorMessage code={error||inputError}/>} {!car?<p role="status">{t('loading')}</p>:<><div className="page-heading"><div><p className="eyebrow">{t('requestType')}</p><h1>{car.name}</h1><Link href={`/${locale}/supplier/${car.supplier_id}`}>{car.supplier_name} <ArrowUpRight/></Link></div><Status value="demonstration"/></div><div className="detail-layout"><div><CarArt car={car} large/><section className="panel"><h2>{t('specs')}</h2><Specs car={car}/></section><section className="panel"><h2>{t('extras')}</h2>{['child_seat','additional_driver'].map(k=><label key={k} className="extra"><span><input type="checkbox" checked={extras.includes(k)} onChange={e=>{setError('');setExtras(x=>e.target.checked?[...x,k]:x.filter(y=>y!==k));}}/>{t(k)}</span><b>{money(car.rate[k]||0,locale)} / {t('daily')}</b></label>)}</section><Policies policy={car.policy}/></div><aside className="sticky-panel">{quote?<><Trip s={quote.snapshot}/><Price snapshot={quote.snapshot}/><button className="button full" onClick={checkout} disabled={busy}>{t('reserve')}<ArrowRight/></button><p className="muted small">{t('checkoutNote')}</p></>:<div role="status">{t('loading')}</div>}</aside></div></> }</div>;
}
function Checkout(){const {locale,t}=useText();const params=useSearchParams();const router=useRouter();const [q,setQ]=useState<Data|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{const raw=sessionStorage.getItem('quote:'+params.get('quote'));if(raw)setQ(JSON.parse(raw));else setError('quote_expired');},[params]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!q)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const b=await api('/bookings',{quoteId:q.id,locale,termsVersion:q.snapshot.termsVersion,acceptTerms:f.get('accept')==='on',customer:{name:f.get('name'),email:f.get('email'),phone:f.get('phone'),licenceYears:Number(f.get('licenceYears'))}});sessionStorage.setItem('booking:'+b.id,b.accessToken);router.push(`/${locale}/booking/${b.id}#${b.accessToken}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="container section"><p className="eyebrow">01 {t('explore')} / 02 {t('requestType')}</p><h1>{t('checkout')}</h1><p className="lead narrow">{t('checkoutNote')}</p>{error&&<ErrorMessage code={error}/>} {q&&<div className="detail-layout"><div><div className="panel"><h2>{q.snapshot.vehicleName}</h2><Trip s={q.snapshot}/></div><form className="panel form-stack" onSubmit={submit}><h2>{t('contactDetails')}</h2><Field label={t('name')}><input name="name" autoComplete="name" maxLength={100} required/></Field><div className="two-columns"><Field label={t('email')}><input name="email" type="email" autoComplete="email" maxLength={254} required/></Field><Field label={t('phone')}><input name="phone" type="tel" autoComplete="tel" maxLength={40} required/></Field></div><Field label={t('licenceYears')}><input name="licenceYears" type="number" min={q.snapshot.policy.minLicenceYears||2} max={80} required/></Field><Policies policy={q.snapshot.policy}/><Link href={`/${locale}/terms`} target="_blank">{t('terms')} · {q.snapshot.termsVersion}</Link><label className="check acceptance"><input name="accept" type="checkbox" required/>{t('accept')}</label><button className="button" disabled={busy}>{busy?t('saving'):t('submit')}<ArrowRight/></button></form></div><aside className="sticky-panel"><Price snapshot={q.snapshot}/><p className="small">{t('expires')}: {date(q.expiresAt,locale)}</p></aside></div>}</div>;
}
function Booking({id}:{id?:string}){
 const {locale,t}=useText();const [b,setB]=useState<Data|null>(null);const [token,setToken]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [copied,setCopied]=useState(false);const [payment,setPayment]=useState<Data|null>(null);
 useEffect(()=>{if(!id)return;const raw=window.location.hash.slice(1)||sessionStorage.getItem('booking:'+id)||'';setToken(raw);if(raw){sessionStorage.setItem('booking:'+id,raw);window.history.replaceState(null,'',window.location.pathname);}},[id]);
 const refresh=useCallback(()=>{if(id&&token)api('/bookings/'+id,undefined,token).then(setB).catch(e=>setError(e.message));},[id,token]);useEffect(()=>{refresh();const timer=setInterval(refresh,15000);return()=>clearInterval(timer);},[refresh]);
 async function action(path:string,body:unknown){setBusy(true);setError('');try{const result=await api(path,body,token);if(path.endsWith('/payment'))setPayment(result);refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!id)return <div className="container section narrow"><p className="eyebrow">{t('bookings')}</p><h1>{t('manage')}</h1><p>{t('accessText')}</p><form className="panel form-stack" onSubmit={e=>{e.preventDefault();try{const url=new URL(String(new FormData(e.currentTarget).get('url')));if(url.origin!==window.location.origin||!/^\/(en|sq|de)\/booking\/[0-9a-f-]{36}$/.test(url.pathname)||url.hash.length!==65)throw Error();window.location.assign(url.toString());}catch{setError('invalid_access_link');}}}><Field label={t('accessLink')}><input name="url" type="url" required/></Field><button className="button">{t('openBooking')}</button></form>{error&&<Notice error>{t('accessInvalid')}</Notice>}</div>;
 return <div className="container section">{error&&<ErrorMessage code={error}/>} {!b?<div role="status">{token?t('loading'):t('accessText')}</div>:<><div className="page-heading"><div><p className="eyebrow">{t('bookingReference')} · {id.slice(0,8).toUpperCase()}</p><h1>{b.status==='awaiting_supplier'?t('requestReceived'):t(b.status)}</h1><p>{b.status==='awaiting_supplier'?t('checkoutNote'):t('noSilentChange')}</p></div><Status value={b.status}/></div><div className="notice access"><ShieldCheck size={24}/><div>{t('accessWarning')}<button className="link-button" onClick={async()=>{await navigator.clipboard.writeText(`${window.location.origin}/${locale}/booking/${id}#${token}`);setCopied(true);}}>{copied?t('copied'):t('copy')}</button></div></div><div className="detail-layout"><div><section className="panel"><h2>{b.snapshot.vehicleName}</h2><Trip s={b.snapshot}/>{b.status==='awaiting_supplier'&&<div className="deadline"><Clock size={22}/><div>{t('responseBy')}<b>{date(b.response_due,locale)}</b></div></div>}<div className="row"><span>{t('payment')}</span><Status value={b.payment_state}/></div><div className="row"><span>{t('refund')}</span><Status value={b.refund_state}/></div></section>{b.status==='awaiting_payment'&&<section className="panel"><h2>{t('testPayment')}</h2><p>{t('paymentNotice')}</p><p>{t('expires')}: {date(b.payment_due,locale)}</p>{!payment?<button className="button" disabled={busy} onClick={()=>action(`/bookings/${id}/payment`,{})}>{t('startPayment')}</button>:<div className="button-row"><button className="button" disabled={busy} onClick={()=>action(`/test-payments/${payment.id}/complete`,{state:'succeeded'})}>{t('testPay')}</button><button className="button secondary" disabled={busy} onClick={()=>action(`/test-payments/${payment.id}/complete`,{state:'failed'})}>{t('testFail')}</button></div>}</section>}<section className="panel"><h2>{t('history')}</h2><ol className="timeline">{b.history.map((h:Data,i:number)=><li key={i}><Status value={h.status}/><time>{date(h.created_at,locale)}</time></li>)}</ol></section>{b.proposals?.filter((p:Data)=>p.state==='open').map((p:Data)=><section className="panel" key={p.id}><h2>{t('replacement')}</h2><h3>{p.snapshot.vehicleName}</h3><p>{p.data.description}</p><Price snapshot={p.snapshot}/><Policies policy={p.snapshot.policy}/><p>{t('expires')}: {date(p.expires_at,locale)}</p><div className="button-row"><button className="button" disabled={busy} onClick={()=>action('/bookings/'+id+'/replacement/'+p.id,{accept:true,termsVersion:p.snapshot.termsVersion})}>{t('acceptReplacement')}</button><button className="button secondary" disabled={busy} onClick={()=>action('/bookings/'+id+'/replacement/'+p.id,{accept:false})}>{t('rejectReplacement')}</button></div></section>)}
{b.status==='completed'&&<form className="panel form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);action('/bookings/'+id+'/review',{rating:Number(f.get('rating')),text:f.get('text')});}}><h2>{t('writeReview')}</h2><Field label={t('rating')}><select name="rating">{[5,4,3,2,1].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></Field><Field label={t('message')}><textarea name="text" required maxLength={2000}/></Field><button className="button" disabled={busy}>{t('submitReview')}</button></form>}
<section className="panel"><h2>{t('notifications')}</h2><p className="small">{t('devMailbox')}</p>{b.notifications.map((n:Data,i:number)=><div className="row" key={i}><span>{t(n.status)}</span><span>{n.locale.toUpperCase()}</span></div>)}</section>{['awaiting_supplier','awaiting_payment','confirmed'].includes(b.status)&&<form className="panel form-stack" onSubmit={e=>{e.preventDefault();action(`/bookings/${id}/transition`,{status:'cancelled',reason:new FormData(e.currentTarget).get('reason')});}}><h3>{t('cancellation')}</h3><p>{b.snapshot.policy.cancellation}</p><Field label={t('reason')}><input name="reason" required maxLength={1000}/></Field><button className="button danger" disabled={busy}>{t('cancelBooking')}</button></form>}<Policies policy={b.snapshot.policy}/></div><aside className="sticky-panel"><Price snapshot={b.snapshot}/></aside></div></>}</div>;
}
function Support(){const {t}=useText();const [saved,setSaved]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <div className="container section narrow"><p className="eyebrow">{t('support')}</p><h1>{t('supportTitle')}</h1><p className="lead">{t('supportText')}</p>{saved?<Notice>{t('supportSuccess')}<p>{t('supportRef')}: {saved}</p></Notice>:<form className="panel form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const f=new FormData(e.currentTarget);const r=await api('/support',{email:f.get('email'),message:f.get('message')});setSaved(r.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Field label={t('email')}><input type="email" name="email" required maxLength={254}/></Field><Field label={t('message')}><textarea name="message" required rows={6} maxLength={4000}/></Field><button className="button" disabled={busy}>{busy?t('saving'):t('send')}<ArrowRight/></button></form>}{error&&<ErrorMessage code={error}/>}</div>;}
function ContentPage({page}:{page:string}){const {locale,t}=useText();const isGuide=page==='guide'||page==='airport';return <div className="container section narrow"><p className="eyebrow">Kosova Rent-A-Car</p><h1>{t(page==='airport'?'airportTitle':isGuide?'guideTitle':page)}</h1><p className="lead">{t(isGuide?'guideIntro':page+'Text')}</p>{isGuide?<>{['Doc','Deposit','Status'].map(k=><section className="panel" key={k}><h2>{t('guide'+k)}</h2><p>{t('guide'+k+'Text')}</p></section>)}<Link className="button" href={`/${locale}`}>{t('explore')}<ArrowRight/></Link></>:<Notice>{t('draft')}</Notice>}</div>;}
function Supplier({id}:{id:string}){const {t,locale}=useText();const [s,setS]=useState<Data|null>(null);const [error,setError]=useState('');useEffect(()=>{api('/suppliers/'+id).then(setS).catch(e=>setError(e.message));},[id]);return <div className="container section narrow">{error&&<ErrorMessage code={error}/>} {s?<><p className="eyebrow">{t('supplier')}</p><h1>{s.name}</h1><Status value="demonstration"/><p className="lead">{s.profile.description}</p><div className="panel"><h2>{t('pickupReturn')}</h2><p>{t('airport')} · {t('city')}</p><p>{s.profile.openHour}:00 – {s.profile.closeHour}:00</p></div><Link className="button" href={`/${locale}`}>{t('explore')}</Link></>:t('loading')}</div>;}
function Login(){const {t,locale}=useText();const [auth,setAuth]=useState<Data|null>(null);useEffect(()=>{api('/auth/config').then(setAuth);},[]);const router=useRouter();const [error,setError]=useState('');const [busy,setBusy]=useState(false);return <div className="container section narrow"><p className="eyebrow">Kosova Rent-A-Car / TEAM</p><h1>{t('login')}</h1><p>{t('loginText')}</p>{auth?.oidc&&<a className="button" href="/api/auth/oidc">{t('signIn')} · SSO / MFA</a>}<form className="panel form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const a=await api('/auth/login',{email:f.get('email'),password:f.get('password')});router.push(`/${locale}/${a.role==='admin'?'admin':'dashboard'}`);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><Field label={t('email')}><input type="email" name="email" autoComplete="username" required/></Field><Field label={t('password')}><input type="password" name="password" autoComplete="current-password" required/></Field><button className="button" disabled={busy}>{busy?t('loading'):t('signIn')}</button>{error&&<ErrorMessage code={error}/>}</form></div>;}
