import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFileSync} from 'node:fs';
const password=process.env.DemoPassword||readFileSync('../../.local/runtime/demo-password.txt','utf8').trim();
test('English customer request connects to supplier acceptance and guest status',async({page,browser})=>{
 await page.goto('/en'); await expect(page.getByRole('heading',{name:/Land. Pick up./})).toBeVisible();
 await page.getByRole('button',{name:'Find my car'}).click();await expect(page.getByRole('heading',{name:'Cars for your journey'})).toBeVisible();
 await page.getByRole('link',{name:'View car',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Your price breakdown'})).toBeVisible();
 await page.getByRole('button',{name:'Continue to request'}).click();await page.getByLabel('Full name',{exact:true}).fill('Browser Test');await page.getByLabel('Email address',{exact:true}).fill('browser@example.invalid');await page.getByLabel('Phone number',{exact:true}).fill('+0000000');await page.getByLabel('Years holding a driving licence').fill('4');await page.getByLabel(/I accept/).check();await page.getByRole('button',{name:'Send booking request'}).click();
 await expect(page.getByRole('heading',{name:'Request received',exact:true})).toBeVisible();const id=page.url().split('/booking/')[1].split('#')[0];await expect(page.getByText('Awaiting supplier',{exact:true}).first()).toBeVisible();
 const team=await browser.newContext();const p=await team.newPage();await p.goto('/en/login');await p.getByLabel('Email address',{exact:true}).fill('supplier@demo.local');await p.getByLabel('Password',{exact:true}).fill(password);await p.getByRole('button',{name:'Sign in',exact:true}).click();await expect(p.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();await p.getByRole('button',{name:'Reservations',exact:true}).click();await p.getByLabel('Booking reference',{exact:true}).fill(id);await p.locator('.booking-rows>button').first().click();const accept=p.locator('form').filter({has:p.getByRole('button',{name:'Accept request',exact:true})});await accept.getByPlaceholder('Reason').fill('Browser journey acceptance');await accept.getByRole('button',{name:'Accept request',exact:true}).click();await expect(p.getByText('Saved successfully.',{exact:true})).toBeVisible();
 await page.reload();await expect(page.getByRole('heading',{name:'Confirmed',exact:true})).toBeVisible();await page.getByLabel('Reason',{exact:true}).fill('End browser test');await page.getByRole('button',{name:'Cancel request / booking'}).click();await expect(page.getByRole('heading',{name:'Cancelled',exact:true})).toBeVisible();await team.close();
});
for(const locale of ['en','sq','de'])test(`${locale}: mobile search, keyboard focus and accessibility`,async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/'+locale);await expect(page.locator('html')).toHaveAttribute('lang',locale);await page.keyboard.press('Tab');await expect(page.locator('.skip')).toBeFocused();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();
 const home=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(home.violations).toEqual([]);
 await page.locator('.search-form button[type="submit"],.search-form button').first().click();await expect(page.locator('.car-card').first()).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations).toEqual([]);
 await page.screenshot({path:`../../artifacts/${locale}-mobile-results.png`,fullPage:true});
});
test('Desktop homepage and administrator tools render without browser errors',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/en');await page.screenshot({path:'../../artifacts/home-desktop.png',fullPage:true});await page.goto('/en/login');await page.getByLabel('Email address',{exact:true}).fill('admin@demo.local');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Overview',exact:true})).toBeVisible();for(const tab of ['Fleet & rates','Documents','Availability','Business','Team access','Support & incidents','Reconciliation','Audit history']){await page.getByRole('button',{name:tab,exact:true}).click();await expect(page.getByRole('heading',{name:tab,exact:true}).first()).toBeVisible();}expect(errors).toEqual([]);await page.screenshot({path:'../../artifacts/admin-desktop.png',fullPage:true});});
