using System.Text.Json.Nodes;
using Npgsql;
namespace Kosova;
public static class Management
{
    static async Task<(NpgsqlConnection,Actor)> Session(HttpContext ctx,Store db) { var c=await db.Open(); try { return(c,await Security.Actor(ctx,c)); } catch { await c.DisposeAsync(); throw; } }
    static void ValidateVehicle(JsonObject data)
    {
        data.Required("name",100); var spec=data.Obj("spec"); var rate=data.Obj("rate"); var p=data.Obj("policy");
        if(spec.I("seats")<2||spec.I("seats")>9||spec.I("luggage")<0||spec.I("luggage")>10||spec.S("transmission") is not("Automatic" or "Manual")) throw new RuleException("invalid_spec");
        if(spec["locations"] is not JsonArray locations||locations.Count==0||locations.Any(x=>x?.GetValue<string>() is not("prn" or "prishtina"))) throw new RuleException("invalid_locations");
        foreach(var k in new[]{"daily","airportFee","returnFee","child_seat","additional_driver","youngDaily","taxBasisPoints","commissionBasisPoints"}) if(rate.I(k)<0||rate.I(k)>1000000) throw new RuleException("invalid_rate");
        if(rate.I("daily")<100||rate.I("taxBasisPoints")>10000||rate.I("commissionBasisPoints")>10000||rate.I("discountPercent")<0||rate.I("discountPercent")>50||rate.I("bufferMinutes",60)<0||rate.I("bufferMinutes",60)>1440||rate.I("minDays",1)<1||rate.I("maxDays",60)>90||rate.I("maxDays",60)<rate.I("minDays",1)) throw new RuleException("invalid_rate");
        if(p.I("minAge",21)<18||p.I("maxAge",80)<p.I("minAge",21)||p.I("deposit")<0||p.I("deposit")>1000000) throw new RuleException("invalid_policy");
        p.Required("version"); p.Required("insurance",4000); p.Required("documents",2000); p.Required("cancellation",4000); p.Required("depositMethod");
        var image=spec.S("image"); if(image.Length>0&&!image.StartsWith("/cars/")&&!image.StartsWith("/api/images/")) throw new RuleException("invalid_image");
        var seasons=rate["seasons"] as JsonArray??new JsonArray(); var ranges=new List<(DateOnly,DateOnly)>();
        foreach(var s in seasons) { if(s==null||!DateOnly.TryParseExact("2000-"+s.S("from"),"yyyy-MM-dd",out var from)||!DateOnly.TryParseExact("2000-"+s.S("to"),"yyyy-MM-dd",out var to)||from>to||s.I("daily")<100||s.I("daily")>1000000||ranges.Any(r=>r.Item1<=to&&from<=r.Item2)) throw new RuleException("invalid_season"); ranges.Add((from,to)); }
    }
    public static void Map(WebApplication app)
    {
        app.MapGet("/api/manage/overview",async(HttpContext ctx,Store db)=> {
            var(c,a)=await Session(ctx,db); await using var scope=c;
            var filter=a.Admin?"":" WHERE supplier_id=$1"; var args=a.Admin?Array.Empty<object?>():new object?[]{a.SupplierId};
            return Results.Ok(new {
                actor=a,
                suppliers=await Store.Query(c,"SELECT id,name,status,demo,profile FROM suppliers"+(a.Admin?"":" WHERE id=$1"),args),
                vehicles=await Store.Query(c,"SELECT * FROM vehicles"+filter+" ORDER BY updated_at DESC",args),
                bookings=await Store.Query(c,"SELECT b.id,b.supplier_id,b.vehicle_id,b.status,b.payment_state,b.refund_state,b.response_due,b.payment_due,b.created_at,q.snapshot FROM bookings b JOIN quotes q ON q.id=b.quote_id"+(a.Admin?"":" WHERE b.supplier_id=$1")+" ORDER BY b.created_at DESC LIMIT 300",args),
                documents=await Store.Query(c,"SELECT id,supplier_id,vehicle_id,kind,expires_on,state,original_name,created_at FROM documents"+filter+" ORDER BY expires_on",args),
                operations=await Store.Query(c,"SELECT * FROM operations"+filter+" ORDER BY created_at DESC LIMIT 300",args),
                allocations=await Store.Query(c,"SELECT a.id,a.vehicle_id,a.booking_id,a.kind,a.note,lower(a.period) AS start,upper(a.period) AS end FROM allocations a JOIN vehicles v ON v.id=a.vehicle_id"+(a.Admin?"":" WHERE v.supplier_id=$1")+" ORDER BY lower(a.period)",args),
                commissions=await Store.Query(c,"SELECT c.*,q.total,q.currency FROM commissions c JOIN bookings b ON b.id=c.booking_id JOIN quotes q ON q.id=b.quote_id"+(a.Admin?"":" WHERE b.supplier_id=$1"),args),
                reviewRequired=await Store.Query(c,"SELECT b.id,b.vehicle_id,q.end_at FROM bookings b JOIN quotes q ON q.id=b.quote_id WHERE b.status IN ('confirmed','awaiting_payment') AND (SELECT count(DISTINCT d.kind) FROM documents d WHERE d.vehicle_id=b.vehicle_id AND d.state='approved' AND d.kind IN ('registration','insurance') AND d.expires_on>=q.end_at::date)<2"+(a.Admin?"":" AND b.supplier_id=$1"),args)
            });
        });
        app.MapPost("/api/manage/suppliers",async(HttpContext ctx,Store db,JsonObject input)=> {
            var(c,a)=await Session(ctx,db); await using var scope=c; Security.Admin(a); var id=Guid.NewGuid(); var name=input.Required("name"); var reason=input.Required("reason");
            await using var tx=await c.BeginTransactionAsync(); await Store.Exec(c,"INSERT INTO suppliers(id,name,demo) VALUES($1,$2,$3)",id,name,app.Services.GetRequiredService<RuntimeOptions>().Demo); await Store.Audit(c,a.Key,"supplier.create",id.ToString(),reason,null,new JsonObject{["name"]=name}); await tx.CommitAsync(); return Results.Ok(new{id});
        });
        app.MapPost("/api/manage/suppliers/{id:guid}",async(HttpContext ctx,Store db,Guid id,JsonObject input)=> {
            var(c,a)=await Session(ctx,db); await using var scope=c; Security.Scope(a,id,true); var reason=input.Required("reason");
            await using var tx=await c.BeginTransactionAsync(); var old=await Store.One(c,"SELECT * FROM suppliers WHERE id=$1 FOR UPDATE",id);
            var status=input.S("status",old.S("status")); if(status!=old.S("status")) Security.Admin(a); if(status is not("pending" or "approved" or "suspended")) throw new RuleException("invalid_status");
            var profile=input["profile"] as JsonObject??old.Obj("profile"); if(profile.I("openHour",8)<0||profile.I("closeHour",20)>24||profile.I("openHour",8)>=profile.I("closeHour",20)) throw new RuleException("invalid_hours");
            if(profile["openDays"] is JsonArray days&&(days.Count==0||days.Any(d=>d!.GetValue<int>()<0||d!.GetValue<int>()>6))) throw new RuleException("invalid_hours"); await Store.Exec(c,"UPDATE suppliers SET name=$2,status=$3,profile=$4::jsonb WHERE id=$1",id,input.S("name",old.S("name")),status,profile.ToJsonString()); await Store.Audit(c,a.Key,"supplier.update",id.ToString(),reason,old,input); await tx.CommitAsync(); return Results.Ok(new{id});
        });
        app.MapGet("/api/manage/users",async(HttpContext ctx,Store db)=> { var(c,a)=await Session(ctx,db); await using var scope=c; if(a.Role=="operator") throw new RuleException("forbidden",403); return await Store.Query(c,"SELECT id,email,role,supplier_id FROM users"+(a.Admin?"":" WHERE supplier_id=$1"),a.Admin?[]:[a.SupplierId]); });
        app.MapPost("/api/manage/users",async(HttpContext ctx,Store db,JsonObject input)=> {
            var(c,a)=await Session(ctx,db); await using var scope=c; var sid=input.G("supplierId"); Security.Scope(a,sid,true); var role=input.S("role"); if(role is not("owner" or "operator")) throw new RuleException("invalid_role"); var email=input.Required("email").ToLowerInvariant(); if(!System.Net.Mail.MailAddress.TryCreate(email,out _)) throw new RuleException("invalid_email"); var local=app.Services.GetRequiredService<RuntimeOptions>().Demo; var password=local?input.Required("password"):Security.Token(); if(password.Length<14) throw new RuleException("weak_password"); var reason=input.Required("reason"); var id=Guid.NewGuid();
            await using var tx=await c.BeginTransactionAsync(); await Store.Exec(c,"INSERT INTO users(id,email,password_hash,role,supplier_id) VALUES($1,$2,$3,$4,$5)",id,email,new Microsoft.AspNetCore.Identity.PasswordHasher<string>().HashPassword(email,password),role,sid); if(!local) await Store.Exec(c,"UPDATE users SET external_subject=$2 WHERE id=$1",id,input.Required("externalSubject")); await Store.Audit(c,a.Key,"user.create",id.ToString(),reason,null,new JsonObject{["role"]=role,["supplierId"]=sid}); await tx.CommitAsync(); return Results.Ok(new{id});
        });
        app.MapPost("/api/manage/vehicles",async(HttpContext ctx,Store db,JsonObject input)=> {
            var(c,a)=await Session(ctx,db); await using var scope=c; var sid=input.G("supplierId"); Security.Scope(a,sid); ValidateVehicle(input); var id=Guid.NewGuid(); var reason=input.Required("reason");
            await using var tx=await c.BeginTransactionAsync(); await Store.Exec(c,"INSERT INTO vehicles(id,supplier_id,name,spec,rate,policy) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6::jsonb)",id,sid,input.S("name"),input.Obj("spec").ToJsonString(),input.Obj("rate").ToJsonString(),input.Obj("policy").ToJsonString()); await Store.Audit(c,a.Key,"vehicle.create",id.ToString(),reason,null,input); await tx.CommitAsync(); return Results.Ok(new{id});
        });
        app.MapPost("/api/manage/vehicles/{id:guid}",async(HttpContext ctx,Store db,Guid id,JsonObject input)=> {
            var(c,a)=await Session(ctx,db); await using var scope=c; var reason=input.Required("reason"); await using var tx=await c.BeginTransactionAsync(); var old=await Store.One(c,"SELECT * FROM vehicles WHERE id=$1 FOR UPDATE",id); Security.Scope(a,old.G("supplier_id"));
            var merged=(JsonObject)old.DeepClone(); foreach(var k in new[]{"name","spec","rate","policy"}) if(input[k]!=null) merged[k]=input[k]!.DeepClone(); ValidateVehicle(merged);
            var status=input.S("status",old.S("status")); if(status is not("draft" or "submitted" or "published" or "withdrawn")) throw new RuleException("invalid_status");
            // Material edits require re-review. Existing immutable booking snapshots are unaffected.
            if(!a.Admin&&old.S("status")=="published"&&input.Any(p=>p.Key is "name" or "spec" or "policy")) status="submitted";
            if(status=="published"&&old.S("status")!="published") { Security.Admin(a); var supplier=await Store.One(c,"SELECT status FROM suppliers WHERE id=$1",old.G("supplier_id")); if(supplier.S("status")!="approved") throw new RuleException("supplier_unapproved"); var docs=await Store.Query(c,"SELECT DISTINCT kind FROM documents WHERE vehicle_id=$1 AND state='approved' AND expires_on>=CURRENT_DATE AND kind IN ('registration','insurance')",id); if(docs.Count!=2) throw new RuleException("documents_required"); }
            await Store.Exec(c,"UPDATE vehicles SET name=$2,spec=$3::jsonb,rate=$4::jsonb,policy=$5::jsonb,status=$6,updated_at=now() WHERE id=$1",id,merged.S("name"),merged.Obj("spec").ToJsonString(),merged.Obj("rate").ToJsonString(),merged.Obj("policy").ToJsonString(),status); await Store.Audit(c,a.Key,"vehicle.update",id.ToString(),reason,old,merged); await tx.CommitAsync(); return Results.Ok(new{id,status});
        });
        app.MapPost("/api/manage/documents",async(HttpContext ctx,Store db,RuntimeOptions opts,IPrivateObjects objects,UploadScanner scanner)=> {
            var(c,a)=await Session(ctx,db); await using var scope=c;
            if(ctx.Request.ContentLength>6*1024*1024) throw new RuleException("file_too_large",413);
            var form=await ctx.Request.ReadFormAsync(); if(!Guid.TryParse(form["supplierId"],out var sid)) throw new RuleException("invalid_id"); Security.Scope(a,sid);
            Guid? vid=Guid.TryParse(form["vehicleId"],out var parsed)?parsed:null;
            if(vid!=null) { var vehicle=await Store.One(c,"SELECT supplier_id FROM vehicles WHERE id=$1",vid); if(vehicle.G("supplier_id")!=sid) throw new RuleException("forbidden",403); }
            if(!DateOnly.TryParse(form["expiresOn"],out var expiry)||expiry<DateOnly.FromDateTime(DateTime.UtcNow)) throw new RuleException("invalid_expiry");
            var kind=form["kind"].ToString(); if(kind is not("registration" or "insurance" or "business" or "photo")) throw new RuleException("invalid_kind");
            if(kind=="photo"&&vid==null) throw new RuleException("vehicle_required"); var file=form.Files.GetFile("file")??throw new RuleException("file_required"); if(file.Length==0||file.Length>5*1024*1024||file.ContentType is not("application/pdf" or "image/jpeg" or "image/png")) throw new RuleException("invalid_file");
            if(kind=="photo"&&file.ContentType=="application/pdf") throw new RuleException("invalid_file"); using var memory=new MemoryStream(); await file.CopyToAsync(memory); var bytes=memory.ToArray(); bool valid=file.ContentType switch { "application/pdf"=>bytes.AsSpan().StartsWith("%PDF-"u8),"image/jpeg"=>bytes.Length>2&&bytes[0]==255&&bytes[1]==216,"image/png"=>bytes.AsSpan().StartsWith(new byte[]{137,80,78,71,13,10,26,10}),_=>false}; if(!valid) throw new RuleException("invalid_file");
            var id=Guid.NewGuid(); var key=id.ToString("N"); await objects.Put(key,bytes,file.ContentType); var scan=await scanner.Scan(bytes);
            await using var tx=await c.BeginTransactionAsync(); await Store.Exec(c,"INSERT INTO documents(id,supplier_id,vehicle_id,kind,expires_on,object_key,original_name,content_type) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",id,sid,vid,kind,expiry,key,Path.GetFileName(file.FileName),file.ContentType); await Store.Exec(c,"UPDATE documents SET scan_state=$2 WHERE id=$1",id,scan); await Store.Audit(c,a.Key,"document.upload",id.ToString(),"Quarantined upload",null,new JsonObject{["state"]="quarantined"}); await tx.CommitAsync(); return Results.Ok(new{id,state="quarantined"});
        });
        app.MapGet("/api/manage/documents/{id:guid}/download",async(HttpContext ctx,Store db,RuntimeOptions opts,IPrivateObjects objects,Guid id)=> { var(c,a)=await Session(ctx,db); await using var scope=c; var d=await Store.One(c,"SELECT * FROM documents WHERE id=$1",id); Security.Scope(a,d.G("supplier_id")); if(d.S("object_key").StartsWith("demo:")) throw new RuleException("demo_document_has_no_file",404); await Store.Audit(c,a.Key,"document.download",id.ToString(),"Authorized private document access",null,null); return Results.File(await objects.Get(d.S("object_key")),"application/octet-stream",d.S("original_name")); });
        app.MapPost("/api/manage/documents/{id:guid}/review",async(HttpContext ctx,Store db,RuntimeOptions opts,Guid id,JsonObject input)=> { var(c,a)=await Session(ctx,db); await using var scope=c; Security.Admin(a); var state=input.S("state"); if(state is not("approved" or "rejected")) throw new RuleException("invalid_status");  var reason=input.Required("reason"); await using var tx=await c.BeginTransactionAsync(); var old=await Store.One(c,"SELECT * FROM documents WHERE id=$1 FOR UPDATE",id); if(state=="approved"&&!opts.Demo&&old.S("scan_state")!="clean") throw new RuleException("scan_required"); await Store.Exec(c,"UPDATE documents SET state=$2 WHERE id=$1",id,state); await Store.Audit(c,a.Key,"document.review",id.ToString(),reason,old,new JsonObject{["state"]=state}); await tx.CommitAsync(); return Results.Ok(new{id,state}); });
        app.MapPost("/api/manage/allocations",async(HttpContext ctx,Store db,JsonObject input)=> { var(c,a)=await Session(ctx,db); await using var scope=c; var v=await Store.One(c,"SELECT * FROM vehicles WHERE id=$1",input.G("vehicleId")); Security.Scope(a,v.G("supplier_id")); var start=Rules.Instant(input.Required("start")); var end=Rules.Instant(input.Required("end")); if(end<=start) throw new RuleException("invalid_interval"); var kind=input.S("kind"); if(kind is not("external" or "maintenance" or "blackout")) throw new RuleException("invalid_kind"); var reason=input.Required("reason"); var id=Guid.NewGuid(); await using var tx=await c.BeginTransactionAsync(); await Store.Exec(c,"INSERT INTO allocations(id,vehicle_id,period,kind,note) VALUES($1,$2,tstzrange($3,$4,'[)'),$5,$6)",id,v.G("id"),start,end.AddMinutes(v.Obj("rate").I("bufferMinutes",60)),kind,reason); await Store.Audit(c,a.Key,"allocation.create",id.ToString(),reason,null,input); await tx.CommitAsync(); return Results.Ok(new{id}); });
        app.MapPost("/api/manage/allocations/{id:guid}/remove",async(HttpContext ctx,Store db,Guid id,JsonObject input)=> { var(c,a)=await Session(ctx,db); await using var scope=c; await using var tx=await c.BeginTransactionAsync(); var row=await Store.One(c,"SELECT a.*,v.supplier_id FROM allocations a JOIN vehicles v ON v.id=a.vehicle_id WHERE a.id=$1 FOR UPDATE OF a",id); Security.Scope(a,row.G("supplier_id")); if(row["booking_id"]!=null) throw new RuleException("use_booking_transition"); var reason=input.Required("reason"); await Store.Exec(c,"DELETE FROM allocations WHERE id=$1",id); await Store.Audit(c,a.Key,"allocation.remove",id.ToString(),reason,null,null); await tx.CommitAsync(); return Results.Ok(new{id}); });
        app.MapPost("/api/manage/operations",async(HttpContext ctx,Store db,JsonObject input)=> { var(c,a)=await Session(ctx,db); await using var scope=c; var sid=input.G("supplierId"); Security.Scope(a,sid); var kind=input.S("kind"); if(kind is not("incident" or "support" or "replacement")) throw new RuleException("invalid_kind"); Guid? bid=Guid.TryParse(input.S("bookingId"),out var b)?b:null; if(bid!=null) { var booking=await Store.One(c,"SELECT supplier_id FROM bookings WHERE id=$1",bid); if(booking.G("supplier_id")!=sid) throw new RuleException("forbidden",403); } var reason=input.Required("reason",4000); var id=Guid.NewGuid(); await using var tx=await c.BeginTransactionAsync(); await Store.Exec(c,"INSERT INTO operations(id,supplier_id,booking_id,kind,data) VALUES($1,$2,$3,$4,$5::jsonb)",id,sid,bid,kind,input.Obj("data").ToJsonString()); await Store.Audit(c,a.Key,"operation.create",id.ToString(),reason,null,input); await tx.CommitAsync(); return Results.Ok(new{id}); });
        app.MapPost("/api/manage/operations/{id:guid}",async(HttpContext ctx,Store db,Guid id,JsonObject input)=> { var(c,a)=await Session(ctx,db); await using var scope=c; var row=await Store.One(c,"SELECT * FROM operations WHERE id=$1",id); Security.Scope(a,row.G("supplier_id")); var state=input.S("state"); if(state is not("open" or "resolved" or "rejected" or "published")) throw new RuleException("invalid_status"); if(row.S("kind")=="review") Security.Admin(a); if(row.S("kind")=="replacement"&&state=="resolved") throw new RuleException("customer_acceptance_required"); var reason=input.Required("reason"); await using var tx=await c.BeginTransactionAsync(); await Store.Exec(c,"UPDATE operations SET state=$2 WHERE id=$1",id,state); await Store.Audit(c,a.Key,"operation.update",id.ToString(),reason,row,input); await tx.CommitAsync(); return Results.Ok(new{id,state}); });
        app.MapGet("/api/manage/audit",async(HttpContext ctx,Store db)=> { var(c,a)=await Session(ctx,db); await using var scope=c; Security.Admin(a); return await Store.Query(c,"SELECT * FROM audit_events ORDER BY id DESC LIMIT 300"); });
        app.MapPost("/api/manage/commissions/{id:guid}/reconcile",async(HttpContext ctx,Store db,Guid id,JsonObject input)=> { var(c,a)=await Session(ctx,db); await using var scope=c; Security.Admin(a); var reason=input.Required("reason"); await using var tx=await c.BeginTransactionAsync(); var old=await Store.One(c,"SELECT * FROM commissions WHERE booking_id=$1 FOR UPDATE",id); await Store.Exec(c,"UPDATE commissions SET state='reconciled' WHERE booking_id=$1",id); await Store.Audit(c,a.Key,"commission.reconcile",id.ToString(),reason,old,new JsonObject{["state"]="reconciled"}); await tx.CommitAsync(); return Results.Ok(new{id}); });
    }
}
