using System.Text.Json.Nodes;
namespace Kosova;
public static class Media
{
    public static void Map(WebApplication app)
    {
        app.MapGet("/api/images/{id:guid}",async(Store db,IPrivateObjects objects,Guid id)=>{await using var c=await db.Open();var d=await Store.One(c,"SELECT d.object_key,d.content_type FROM documents d JOIN vehicles v ON v.id=d.vehicle_id JOIN suppliers s ON s.id=v.supplier_id WHERE d.id=$1 AND d.kind='photo' AND d.state='approved' AND v.status='published' AND s.status='approved'",id);return Results.File(await objects.Get(d.S("object_key")),d.S("content_type"));});
        app.MapPost("/api/manage/vehicles/{id:guid}/photo",async(HttpContext ctx,Store db,Guid id,JsonObject input)=>{await using var c=await db.Open();var actor=await Security.Actor(ctx,c);await using var tx=await c.BeginTransactionAsync();var v=await Store.One(c,"SELECT * FROM vehicles WHERE id=$1 FOR UPDATE",id);Security.Scope(actor,v.G("supplier_id"));var d=await Store.One(c,"SELECT * FROM documents WHERE id=$1 AND vehicle_id=$2 AND kind='photo' AND state='approved'",input.G("documentId"),id);var spec=(JsonObject)v.Obj("spec").DeepClone();var path="/api/images/"+d.S("id");spec["image"]=path;var images=spec["images"] as JsonArray??new JsonArray();if(!images.Any(x=>x?.ToString()==path))images.Add(path);if(spec["images"]==null)spec["images"]=images;await Store.Exec(c,"UPDATE vehicles SET spec=$2::jsonb WHERE id=$1",id,spec.ToJsonString());await Store.Audit(c,actor.Key,"vehicle.photo",id.ToString(),input.Required("reason"),v.Obj("spec"),spec);await tx.CommitAsync();return Results.Ok(new{id,image=path});});
        app.MapPost("/api/manage/users/{id:guid}/revoke",async(HttpContext ctx,Store db,Guid id,JsonObject input)=>{await using var c=await db.Open();var a=await Security.Actor(ctx,c);var u=await Store.One(c,"SELECT id,role,supplier_id FROM users WHERE id=$1",id);if(u.S("role")=="admin")Security.Admin(a);else Security.Scope(a,u.G("supplier_id"),true);if(a.Id==id)throw new RuleException("cannot_revoke_self");await using var tx=await c.BeginTransactionAsync();await Store.Exec(c,"DELETE FROM sessions WHERE user_id=$1",id);await Store.Exec(c,"UPDATE users SET password_hash='revoked',external_subject=null WHERE id=$1",id);await Store.Audit(c,a.Key,"user.revoke",id.ToString(),input.Required("reason"),u,null);await tx.CommitAsync();return Results.Ok(new{id});});
        app.MapGet("/api/manage/notifications",async(HttpContext ctx,Store db)=>{await using var c=await db.Open();Security.Admin(await Security.Actor(ctx,c));return await Store.Query(c,"SELECT id,booking_id,status,locale,state,attempts,available_at,delivered_at FROM notification_jobs ORDER BY available_at DESC LIMIT 300");});
        app.MapPost("/api/manage/notifications/{id:guid}/retry",async(HttpContext ctx,Store db,Guid id,JsonObject input)=>{await using var c=await db.Open();var a=await Security.Actor(ctx,c);Security.Admin(a);await using var tx=await c.BeginTransactionAsync();await Store.Exec(c,"UPDATE notification_jobs SET state='pending',attempts=0,available_at=now() WHERE id=$1 AND state='failed'",id);await Store.Audit(c,a.Key,"notification.retry",id.ToString(),input.Required("reason"),null,null);await tx.CommitAsync();return Results.Ok(new{id});});
    }
}
